# Copyright 2026 Roderick Consulting Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Markdown specification-page generator — the third Babel lockstep output.

The interpreter (`babel.interpreter`, `babel.stack_interpreter`,
`babel.oisc_interpreter`, `babel.fungeoid_interpreter`) and the
transpiler (`babel.transpiler`) emit runtime behaviour. The generator
in this module emits prose: a self-contained Markdown specification of
the language a parameter sheet defines. Together the three close the
"interpreter + transpiler + spec page" target structure §5 of the
methodology paper described as lockstep.

The spec page is intentionally derivable mechanically from the
``LanguageSpec`` alone. No information that is not in the parameter
sheet flows into it; everything in the sheet that is visible to a
language user shows up.
"""

from __future__ import annotations

from babel.schema import LanguageSpec, MetaParameters, ExampleProgram


def render_spec(spec: LanguageSpec) -> str:
    """Render the parameter sheet as a Markdown specification page."""
    parts: list[str] = []
    parts.append(f"# {spec.name} — Specification\n\n")
    parts.append(f"*Version {spec.version}. Generated by Babel runtime.*\n")
    if spec.description:
        parts.append("\n## Overview\n\n")
        parts.append(spec.description.strip() + "\n")
    parts.append("\n## Mechanical parameters\n\n")
    parts.append(_render_mechanical_table(spec))
    parts.append("\n## Instruction set\n\n")
    parts.append(_render_instructions_table(spec))
    if spec.additions or spec.removals:
        parts.append("\n## Departures from the base instruction set\n")
        if spec.additions:
            parts.append("\n**Additions:**\n\n")
            for a in spec.additions:
                parts.append(f"- `{a}`\n")
        if spec.removals:
            parts.append("\n**Removals:**\n\n")
            for r in spec.removals:
                parts.append(f"- `{r}`\n")
    parts.append("\n## Meta-parameters (design intent)\n\n")
    parts.append(_render_meta_table(spec.meta))
    if spec.examples:
        parts.append("\n## Example programs\n\n")
        for ex in spec.examples:
            parts.append(_render_example(ex, spec))
    return "".join(parts)


def _render_mechanical_table(spec: LanguageSpec) -> str:
    rows = [
        ("Base machine", spec.base_machine.value),
        ("Memory shape", spec.memory_shape.value),
        ("Cell width", spec.cell_width.value),
        ("Encoding", spec.encoding.value),
        ("I/O model", spec.io.value),
    ]
    if spec.theme:
        rows.append(("Theme", spec.theme))
    if spec.source_extension:
        rows.append(("Source extension", f"`{spec.source_extension}`"))
    out = "| Parameter | Value |\n| --- | --- |\n"
    for name, value in rows:
        out += f"| {name} | `{value}` |\n"
    return out


def _render_instructions_table(spec: LanguageSpec) -> str:
    has_arity = any(i.arity for i in spec.instructions)
    has_desc = any(i.description for i in spec.instructions)
    header = ["Token", "Operation"]
    if has_arity:
        header.append("Arity")
    if has_desc:
        header.append("Description")
    out = "| " + " | ".join(header) + " |\n"
    out += "| " + " | ".join("---" for _ in header) + " |\n"
    for inst in spec.instructions:
        cells = [f"`{_escape_pipes(inst.token)}`", inst.op.value]
        if has_arity:
            cells.append(str(inst.arity))
        if has_desc:
            cells.append(inst.description.strip() if inst.description else "")
        out += "| " + " | ".join(cells) + " |\n"
    return out


def _render_meta_table(meta: MetaParameters) -> str:
    rows = [
        ("Complexity", meta.complexity),
        ("Abstraction", meta.abstraction),
        ("Verbosity", meta.verbosity),
        ("Playfulness", meta.playfulness),
        ("Unpredictability", meta.unpredictability),
        ("Naturalness", meta.naturalness),
    ]
    set_rows = [(n, v) for n, v in rows if v is not None]
    if not set_rows:
        return "_No meta-parameters set on this sheet._\n"
    out = "| Parameter | Value |\n| --- | --- |\n"
    for name, value in set_rows:
        out += f"| {name} | `{value}` |\n"
    return out


def _render_example(ex: ExampleProgram, spec: LanguageSpec) -> str:
    out = f"### {ex.title}\n\n"
    if ex.description:
        out += ex.description.strip() + "\n\n"
    lang_hint = _code_fence_lang(spec)
    out += f"```{lang_hint}\n{ex.source.strip()}\n```\n"
    if ex.expected_output is not None:
        out += "\n**Expected output:**\n\n"
        # Render output as a fenced block so leading whitespace is preserved.
        out += "```\n" + ex.expected_output + "\n```\n"
    out += "\n"
    return out


def _code_fence_lang(spec: LanguageSpec) -> str:
    """Pick a code-fence language hint from the source extension, if any."""
    if spec.source_extension:
        # Drop the leading dot; pandoc and most renderers accept anything
        # short and word-like in the fence-info string. If the extension
        # is unfamiliar to the renderer it falls back to plain code, which
        # is fine.
        return spec.source_extension.lstrip(".")
    return ""


def _escape_pipes(s: str) -> str:
    """Markdown tables use `|` as a column delimiter; escape any in cell text."""
    return s.replace("|", r"\|")
